%{?!ros_distro:%global ros_distro lyrical}
%global pkg_name async_web_server_cpp
%global normalized_pkg_name %{lua:return (string.gsub(rpm.expand('%{pkg_name}'), '_', '-'))}

Name:           ros-lyrical-async-web-server-cpp
Version:        2.0.1
Release:        3%{?dist}
Summary:        ROS %{pkg_name} package

License:        BSD
URL:            http://ros.org/wiki/async_web_server_cpp
Source0:        %{name}-%{version}.tar.gz

BuildRequires:  bloom-rpm-macros
BuildRequires:  cmake

%{?bloom_package}

%description
Asynchronous Web/WebSocket Server in C++


%package devel
Release:        %{release}%{?release_suffix}
Summary:        %{summary}
Provides:       %{name} = %{version}-%{release}
Provides:       %{name}%{?_isa} = %{version}-%{release}
Requires:       %{name}-runtime%{?_isa} = %{version}-%{release}

%description devel
Asynchronous Web/WebSocket Server in C++


%package runtime
Release:        %{release}
Summary:        %{summary}

%description runtime
Asynchronous Web/WebSocket Server in C++


%prep
%autosetup -p1


%generate_buildrequires
%bloom_buildrequires


%build
%cmake \
    -UINCLUDE_INSTALL_DIR \
    -ULIB_INSTALL_DIR \
    -USYSCONF_INSTALL_DIR \
    -USHARE_INSTALL_PREFIX \
    -ULIB_SUFFIX \
    -DCMAKE_INSTALL_PREFIX="%{bloom_prefix}" \
    -DCMAKE_PREFIX_PATH="%{bloom_prefix}" \
    -DSETUPTOOLS_DEB_LAYOUT=OFF \
    -DCATKIN_BUILD_BINARY_PACKAGE="1" \
%if !0%{?with_tests}
    -DBUILD_TESTING=OFF \
    -DCATKIN_ENABLE_TESTING=OFF \
%endif

%cmake3_build


%install
%cmake_install


%files devel
%dir %{bloom_prefix}
%ghost %{bloom_prefix}/share/%{pkg_name}/package.xml


%files runtime
%{bloom_prefix}


%changelog
* Wed Apr 29 2026 Timo Röhling <timo.roehling@fkie.fraunhofer.de> - 2.0.1-3
- Autogenerated by Bloom

* Tue Apr 28 2026 Timo Röhling <timo.roehling@fkie.fraunhofer.de> - 2.0.1-2
- Autogenerated by Bloom

* Tue Apr 21 2026 Timo Röhling <timo.roehling@fkie.fraunhofer.de> - 2.0.1-1
- Autogenerated by Bloom
